### ISSUE TITLE
Provide info on why check failed and what action can be taken to fix it

### ISSUE THREAD

**Issue by jegli** [merkle-open/env-linter#11]
If one of the checks fails, it would be nice to provide more information on why it failed and what actions can be taken to fix it.

To make sure the output on the CLI is not too extensive, we could add some kind of `Why is this?` - link at the end of a failed check. Preferably the additional information is stored in a separate folder (e.g. `docs`) which contains several markdown files for the individual errors that could occur.

Thanks @jantimon for this suggestion. I am sure this will help new developers understand the errors better. 🤓

**Comment by dmodalek** [comment]
I've added a docs folder with explanations for each warning: https://github.com/namics/env-linter/pull/12

What do you think?

**Comment by jegli** [comment]
Has been merged. Thanks again @dmodalek 🙏
