### ISSUE TITLE
use generic package name

### ISSUE THREAD

**Issue by ernscht** [merkle-open/env-linter#16]
We should remove the env-linter from the scope @namics and use a generic name. (e.g. envlinter, environment-linter, ...)

**Comment by danielkoch** [comment]
I like the name envlinter

**Comment by ernscht** [comment]
That would be great, of course. 
And all the criteria for unpublishing should be met. (https://docs.npmjs.com/policies/unpublish#packages-published-more-than-72-hours-ago)

**Comment by seanperkins** [comment]
This is complete so feel free to snatch it up before someone else does.

**Comment by ernscht** [comment]
Cool. Thank you very much @seanperkins 
Re-publishing works at the earliest 24h after unpublishing. Will try it tomorrow.

**Comment by ernscht** [comment]
published to npm as version 0.5.1 https://www.npmjs.com/package/env-linter
thank you again
