### ISSUE TITLE
Env linter is validating other folders with a package json

### ISSUE THREAD

**Issue by janwidmer** [merkle-open/env-linter#17]
Whan having the following setup:

Project Root (git root)
    - Folder a (Package json)
    - Folder b (Package json with env linter)

Folder a contains a 3rd Party Folder having a package json.
Folder b contains my Project with the env Linter.

The problem is, that when running `npm i` from Folder b, the env linter also checks the package in Folder a which does not have a valid package json according to the env linter rules.

You can reproduce the problem by checking out this repo: https://github.com/janwidmer/env-linter-bug

and do the following steps:

1. Open the terminal
2. Go into the folder `wp-content/themes/my-theme`
3. Run `npm i`
4. See the error:

```
✖ Not all devDependencies in twentynineteen have been declared by exact version(s). Why is this? (​https://github.com/merkle-open/env-linter/tree/master/docs/dependenciesExactVersion.md​) 
	- [@wordpress/browserslist-config] Approximate version identifier "^" is not allowed.
	- [autoprefixer] Approximate version identifier "^" is not allowed.
	- [chokidar-cli] Approximate version identifier "^" is not allowed.
	- [node-sass] Approximate version identifier "^" is not allowed.
	- [npm-run-all] Approximate version identifier "^" is not allowed.
	- [postcss-cli] Approximate version identifier "^" is not allowed.
	- [postcss-focus-within] Approximate version identifier "^" is not allowed.
	- [rtlcss] Approximate version identifier "^" is not allowed..
```

**Comment by jegli** [comment]
Hi @janwidmer 

Thanks for reporting this and for providing a repo to easily reproduce the bug. 👍

I think the problem stems from the fact that you cd into the root-folder, install husky and then run the env-linter from the root-directory. Here is your `package.json` from `wp-content/themes/my-theme`:
`"postinstall": "cd ../../../ && husky install && env-linter --hooksInstalled --saveExact --dependenciesExactVersion --lts"`

You can fix this by changing this line to:
`"postinstall": "cd ../../../ && husky install && cd wp-content/themes/my-theme && env-linter --hooksInstalled --saveExact --dependenciesExactVersion --lts"`

Or maybe even better, split it up into multiple postinstall scripts as follows:
```
"postinstall": "npm-run-all postinstall:*",
"postinstall:husky": "cd ../../../ && husky install",
"postinstall:env-linter": "env-linter --hooksInstalled --saveExact --dependenciesExactVersion --lts",
```

Let me know if this works for you. ✌️

**Comment by janwidmer** [comment]
great, when doing it like this, it's working. thanks.
