### ISSUE TITLE
CodeQL v1 is deprecated

### ISSUE THREAD

**Issue by malinovic** [merkle-open/env-linter#39]
The automatic code quality checking and analysis was not working since 1. January 2022. What was noticed is, that it is already deprecated and the version v2 is out. 

### Goal

- Use new code quality v2 ([read more](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/))
- Ensure good coverage and functionality

**Comment by ernscht** [comment]
[v2 is also deprecated](https://github.com/github/codeql-action?tab=readme-ov-file#supported-versions-of-the-codeql-action).

so, it's a good decision to upgrade to v3
