### ISSUE TITLE
save-exact with ci

### ISSUE THREAD

**Issue by MartinCerny-awin** [merkle-open/env-linter#40]
What is the point of validating save-exact when running `npm ci`. Is it happening because we are not able to distinguish between `npm install` and `npm ci`? 

How am I supposed to handle errors in GitHub Actions which is happening because I do not have there `save-exact=true`?

**Comment by MartinCerny-awin** [comment]
I am closing issue as I have solved it by adding `.npmrc` with `save-exact=true` into my repository and using it when running `npm ci`

**Comment by ernscht** [comment]
You were able to solve the problem yourself, great.

Here are a few more explanations:
You have found the right solution for the "save-exact" test. This should help you to have more reproducible setups. ([Explanations about save-exact](https://github.com/merkle-open/env-linter/blob/master/docs/saveExact.md))

But of course you only need to activate the tests that you actually need. See [usage example](https://github.com/merkle-open/env-linter?tab=readme-ov-file#usage-example)
And for the CI environment, you can deactivate the tests with an environment variable: 'ENV_LINTER_SKIP=true' (see also in the [usage example](https://github.com/merkle-open/env-linter?tab=readme-ov-file#usage-example))
