### ISSUE TITLE
`NPM save-exact is turned off` but I have `save-exact=true`

### ISSUE THREAD

**Issue by binary64** [merkle-open/env-linter#41]
Hi, I am facing a problem on a fresh install of Ubuntu:

```
$ yarn env-linter -s || cat .npmrc
yarn run v1.22.19
$ /home/user/repos/bitbucket.org/monorepo/node_modules/.bin/env-linter -s
✖ NPM save-exact is turned off. Why is this?
Stopping any further processes!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
auto-install-peers=false
strict-peer-dependencies=false
save-exact=true
```
I get this same error with both 1.0.0 and 2.0.0

**Comment by malinovic** [comment]
Hello @binary64,

Can you provide more context to it:

- Are you using it in a monorepo?
- What node version are you using?

**Comment by binary64** [comment]
I installed Node using the Snap store

**Comment by malinovic** [comment]
If you are passing the `-s` flag to the env-linter,  then a `.npmrc` file is required to be present in the root of the project, with `save-exact=true` set. If you have a global .npmrc file defined but not locally in the project, running env-linter with `-s` will fail. 

Therefore, Can you provide us more context to the issue that you are facing:
- Which node version are you using?
- Which env-linter version have you installed on the project.
- Where is the .npmrc file located?

**Comment by binary64** [comment]
There is a .npmrc in my root, which is also the pwd. I uninstalled node from snap and installed using nvm and now it works, so definitely it's that.

If you wanted to replicate, I just installed latest Ubuntu desktop in a VM and installed node via the app store.

**Comment by binary64** [comment]
Ok. As a suggestion: the readme could mention this fact. Keep up the good work. Very much appreciate you.
